// <auto-generated />
using System;
using AutoMecanic.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoMecanic.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(AutoMecanicDbContext))]
    [Migration("20260828024346_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("automecanic")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoMecanic.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CadastradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_cliente_ativo");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ux_cliente_documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cliente_nome");

                    b.ToTable("cliente", "automecanic", t =>
                        {
                            t.HasComment("Clientes atendidos pela oficina, pessoa física ou jurídica.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Estoque.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid?>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("uuid")
                        .HasColumnName("peca_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_anterior");

                    b.Property<int>("SaldoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_atual");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_movimento_estoque");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_movimento_estoque_ordem_servico");

                    b.HasIndex("PecaId", "OcorridoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_movimento_estoque_peca_data");

                    b.ToTable("movimento_estoque", "automecanic", t =>
                        {
                            t.HasComment("Razão append-only de todas as movimentações de estoque.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Estoque.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CadastradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("QuantidadeEmEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_em_estoque");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_reservada");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade_medida");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_peca");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_peca_ativo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_peca_codigo");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_peca_nome");

                    b.ToTable("peca", "automecanic", t =>
                        {
                            t.HasComment("Peças e insumos controlados pelo estoque da oficina.");

                            t.HasCheckConstraint("ck_peca_preco_positivo", "preco_unitario > 0");

                            t.HasCheckConstraint("ck_peca_reserva_menor_que_saldo", "quantidade_reservada <= quantidade_em_estoque");

                            t.HasCheckConstraint("ck_peca_reserva_nao_negativa", "quantidade_reservada >= 0");

                            t.HasCheckConstraint("ck_peca_saldo_nao_negativo", "quantidade_em_estoque >= 0");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTimeOffset>("CadastradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("character varying(72)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_falhas");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_email");

                    b.HasIndex("Perfil")
                        .HasDatabaseName("ix_usuario_perfil");

                    b.ToTable("usuario", "automecanic", t =>
                        {
                            t.HasComment("Usuários administrativos com acesso às APIs protegidas por JWT.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.OrdensServico.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao_problema");

                    b.Property<string>("DiagnosticoTecnico")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("diagnostico_tecnico");

                    b.Property<DateTimeOffset?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregue_em");

                    b.Property<DateTimeOffset?>("ExecucaoIniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execucao_iniciada_em");

                    b.Property<DateTimeOffset?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizada_em");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("numero");

                    b.Property<int?>("QuilometragemEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem_entrada");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_ordem_servico_cliente_id");

                    b.HasIndex("CriadaEm")
                        .HasDatabaseName("ix_ordem_servico_criada_em");

                    b.HasIndex("FinalizadaEm")
                        .HasDatabaseName("ix_ordem_servico_finalizada_em");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_ordem_servico_numero");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ordem_servico_status");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_ordem_servico_veiculo_id");

                    b.ToTable("ordem_servico", "automecanic", t =>
                        {
                            t.HasComment("Ordens de Serviço: o agregado central do sistema.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Servicos.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CadastradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cadastrado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("preco");

                    b.Property<int>("TempoEstimadoEmMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_estimado_em_minutos");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_servico");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("ix_servico_categoria");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_servico_nome");

                    b.ToTable("servico", "automecanic", t =>
                        {
                            t.HasComment("Catálogo de serviços prestados, com preço de tabela e tempo estimado.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Veiculos.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("integer")
                        .HasColumnName("ano_fabricacao");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("integer")
                        .HasColumnName("ano_modelo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CadastradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cadastrado_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cor");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("placa");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_veiculo");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_veiculo_ativo");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_veiculo_cliente_id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ux_veiculo_placa");

                    b.ToTable("veiculo", "automecanic", t =>
                        {
                            t.HasComment("Veículos atendidos pela oficina, vinculados a um cliente.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Infrastructure.Persistencia.SequenciaOrdemServico", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("UltimoValor")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_valor");

                    b.HasKey("Ano")
                        .HasName("pk_sequencia_ordem_servico");

                    b.ToTable("sequencia_ordem_servico", "automecanic", t =>
                        {
                            t.HasComment("Contador do número sequencial de Ordem de Serviço, reiniciado a cada ano.");
                        });
                });

            modelBuilder.Entity("AutoMecanic.Domain.Clientes.Cliente", b =>
                {
                    b.OwnsOne("AutoMecanic.Domain.Clientes.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("endereco_uf");

                            b1.HasKey("ClienteId")
                                .HasName("pk_cliente");

                            b1.ToTable("cliente", "automecanic");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId")
                                .HasConstraintName("fk_cliente_cliente_id");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AutoMecanic.Domain.Estoque.MovimentoEstoque", b =>
                {
                    b.HasOne("AutoMecanic.Domain.Estoque.Peca", null)
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimento_estoque_peca");
                });

            modelBuilder.Entity("AutoMecanic.Domain.OrdensServico.OrdemServico", b =>
                {
                    b.HasOne("AutoMecanic.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_cliente");

                    b.HasOne("AutoMecanic.Domain.Veiculos.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_veiculo");

                    b.OwnsMany("AutoMecanic.Domain.OrdensServico.HistoricoStatus", "_historico", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Observacao")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("observacao");

                            b1.Property<DateTimeOffset>("OcorridoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ocorrido_em");

                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.Property<string>("StatusAnterior")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("status_anterior");

                            b1.Property<string>("StatusAtual")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("status_atual");

                            b1.Property<Guid?>("UsuarioId")
                                .HasColumnType("uuid")
                                .HasColumnName("usuario_id");

                            b1.HasKey("Id")
                                .HasName("pk_ordem_servico_historico");

                            b1.HasIndex("OrdemServicoId", "OcorridoEm")
                                .HasDatabaseName("ix_ordem_servico_historico_ordem_data");

                            b1.ToTable("ordem_servico_historico", "automecanic", t =>
                                {
                                    t.HasComment("Linha do tempo de transições de status da OS.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId")
                                .HasConstraintName("fk_ordem_servico_historico_ordem_servico_ordem_servico_id");
                        });

                    b.OwnsMany("AutoMecanic.Domain.OrdensServico.ItemPeca", "_itensPeca", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AdicionadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("adicionado_em");

                            b1.Property<string>("CodigoPeca")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("codigo_peca");

                            b1.Property<bool>("Consumida")
                                .HasColumnType("boolean")
                                .HasColumnName("consumida");

                            b1.Property<string>("NomePeca")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("nome_peca");

                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.Property<Guid>("PecaId")
                                .HasColumnType("uuid")
                                .HasColumnName("peca_id");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.Property<bool>("Reservada")
                                .HasColumnType("boolean")
                                .HasColumnName("reservada");

                            b1.HasKey("Id")
                                .HasName("pk_ordem_servico_item_peca");

                            b1.HasIndex("OrdemServicoId")
                                .HasDatabaseName("ix_ordem_servico_item_peca_ordem_servico_id");

                            b1.HasIndex("PecaId")
                                .HasDatabaseName("ix_ordem_servico_item_peca_peca_id");

                            b1.ToTable("ordem_servico_item_peca", "automecanic", t =>
                                {
                                    t.HasComment("Peças previstas em uma OS, com preço congelado e situação de reserva.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId")
                                .HasConstraintName("fk_ordem_servico_item_peca_ordem_servico_ordem_servico_id");
                        });

                    b.OwnsMany("AutoMecanic.Domain.OrdensServico.ItemServico", "_itensServico", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AdicionadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("adicionado_em");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("descricao");

                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("servico_id");

                            b1.Property<int>("TempoEstimadoEmMinutos")
                                .HasColumnType("integer")
                                .HasColumnName("tempo_estimado_em_minutos");

                            b1.HasKey("Id")
                                .HasName("pk_ordem_servico_item_servico");

                            b1.HasIndex("OrdemServicoId")
                                .HasDatabaseName("ix_ordem_servico_item_servico_ordem_servico_id");

                            b1.HasIndex("ServicoId")
                                .HasDatabaseName("ix_ordem_servico_item_servico_servico_id");

                            b1.ToTable("ordem_servico_item_servico", "automecanic", t =>
                                {
                                    t.HasComment("Serviços contratados em uma OS, com preço congelado na inclusão.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId")
                                .HasConstraintName("fk_ordem_servico_item_servico_ordem_servico_ordem_servico_id");
                        });

                    b.OwnsOne("AutoMecanic.Domain.OrdensServico.Orcamento", "Orcamento", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("EnviadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("enviado_em");

                            b1.Property<DateTimeOffset>("GeradoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("gerado_em");

                            b1.Property<string>("MotivoReprovacao")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("motivo_reprovacao");

                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.Property<decimal>("PercentualDesconto")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("percentual_desconto");

                            b1.Property<DateTimeOffset?>("RespondidoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("respondido_em");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset?>("ValidoAte")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valido_ate");

                            b1.Property<decimal>("ValorPecas")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("valor_pecas");

                            b1.Property<decimal>("ValorServicos")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("valor_servicos");

                            b1.Property<decimal>("ValorTotal")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("valor_total");

                            b1.HasKey("Id")
                                .HasName("pk_orcamento");

                            b1.HasIndex("OrdemServicoId")
                                .IsUnique()
                                .HasDatabaseName("ix_orcamento_ordem_servico_id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_orcamento_status");

                            b1.HasIndex("ValidoAte")
                                .HasDatabaseName("ix_orcamento_valido_ate");

                            b1.ToTable("orcamento", "automecanic", t =>
                                {
                                    t.HasComment("Orçamento gerado automaticamente a partir dos itens da OS.");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId")
                                .HasConstraintName("fk_orcamento_ordem_servico_ordem_servico_id");
                        });

                    b.Navigation("Orcamento");

                    b.Navigation("_historico");

                    b.Navigation("_itensPeca");

                    b.Navigation("_itensServico");
                });

            modelBuilder.Entity("AutoMecanic.Domain.Veiculos.Veiculo", b =>
                {
                    b.HasOne("AutoMecanic.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculo_cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
